"""
Triangle Wave Generation from Variable Duty Cycle PWM and RC Filtering

This simulation demonstrates how a triangle wave can be generated by:
1. Creating a PWM signal with linearly varying duty cycle
2. Filtering the PWM through an RC low-pass filter
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import signal
from util import si_formatter


def generate_pwm_signal(t, f_pwm, duty_cycle_func):
    """
    Generate PWM signal with time-varying duty cycle

    Parameters:
    -----------
    t : array
        Time array
    f_pwm : float
        PWM carrier frequency (Hz)
    duty_cycle_func : callable
        Function that returns duty cycle (0-1) for given time

    Returns:
    --------
    pwm : array
        PWM signal (0 or 1)
    """
    pwm = np.zeros_like(t)
    T_pwm = 1 / f_pwm

    for i, time in enumerate(t):
        # Current position within PWM period
        phase = (time % T_pwm) / T_pwm
        duty = duty_cycle_func(time)
        pwm[i] = 1.0 if phase < duty else 0.0

    return pwm


def rc_filter(signal_in, fs, R, C):
    """
    Apply RC low-pass filter to input signal

    Parameters:
    -----------
    signal_in : array
        Input signal
    fs : float
        Sampling frequency (Hz)
    R : float
        Resistance (Ohms)
    C : float
        Capacitance (Farads)

    Returns:
    --------
    filtered : array
        Filtered signal
    """
    # RC filter cutoff frequency
    fc = 1 / (2 * np.pi * R * C)

    # Design digital filter using bilinear transform
    b, a = signal.butter(1, fc, fs=fs, btype="low", analog=False)

    # Apply filter
    filtered = signal.filtfilt(b, a, signal_in)

    return filtered


def triangle_wave(t, f_tri, amplitude=1.0, offset=0.5):
    """
    Generate ideal triangle wave for comparison

    Parameters:
    -----------
    t : array
        Time array
    f_tri : float
        Triangle wave frequency (Hz)
    amplitude : float
        Peak amplitude (default: 1.0 for 0-1 range)
    offset : float
        DC offset (default: 0.5 for 0-1 range)

    Returns:
    --------
    tri : array
        Triangle wave
    """
    return amplitude * signal.sawtooth(2 * np.pi * f_tri * t, width=0.5) + offset


def simulate_pwm_triangle_generation(f_tri=10, f_pwm=1000, R=10e3, C=10e-6, duration=0.5, samples_per_pwm_period=100):
    """
    Main simulation function

    Parameters:
    -----------
    f_tri : float
        Desired triangle wave frequency (Hz)
    f_pwm : float
        PWM carrier frequency (Hz)
    R : float
        Filter resistance (Ohms)
    C : float
        Filter capacitance (Farads)
    duration : float
        Simulation duration (seconds)
    samples_per_pwm_period : int
        Number of samples per PWM period
    """

    # Calculate sampling frequency
    fs = f_pwm * samples_per_pwm_period

    # Time array
    t = np.linspace(0, duration, int(fs * duration))

    # Define duty cycle function (triangle wave modulation)
    # Duty cycle varies from 0 to 1 in a triangular pattern
    def duty_cycle_func(time):
        # Triangle wave oscillating between 0 and 1
        return 0.5 * (1 + signal.sawtooth(2 * np.pi * f_tri * time, width=0.5))

    # Generate PWM signal
    print("Generating PWM signal...")
    pwm = generate_pwm_signal(t, f_pwm, duty_cycle_func)

    # Apply RC filter
    print("Applying RC filter...")
    filtered = rc_filter(pwm, fs, R, C)

    # Generate ideal triangle wave for comparison
    ideal_triangle = triangle_wave(t, f_tri, amplitude=0.5, offset=0.5)

    # Calculate filter parameters
    fc = 1 / (2 * np.pi * R * C)

    # Print simulation parameters
    print("\n" + "=" * 60)
    print("SIMULATION PARAMETERS")
    print("=" * 60)
    print(f"Triangle wave frequency:  {si_formatter(f_tri, 'Hz')}")
    print(f"PWM carrier frequency:    {si_formatter(f_pwm, 'Hz')}")
    print(f"PWM/Triangle ratio:       {f_pwm/f_tri:.1f}")
    print(f"Filter resistance:        {si_formatter(R, 'Ω')}")
    print(f"Filter capacitance:       {si_formatter(C, 'F')}")
    print(f"Filter cutoff frequency:  {si_formatter(fc, 'Hz')}")
    print(f"Sampling frequency:       {si_formatter(fs, 'Hz')}")
    print(f"Duration:                 {si_formatter(duration, 's')}")
    print("=" * 60 + "\n")

    # Create visualization
    fig, axes = plt.subplots(4, 1, figsize=(12, 10))
    fig.suptitle("Triangle Wave Generation from Variable Duty Cycle PWM", fontsize=14, fontweight="bold")

    # Plot 1: Duty cycle over time
    duty_values = np.array([duty_cycle_func(ti) for ti in t])
    axes[0].plot(t * 1000, duty_values * 100, "b-", linewidth=1.5)
    axes[0].set_ylabel("Duty Cycle (%)")
    axes[0].set_title("PWM Duty Cycle Modulation")
    axes[0].grid(True, alpha=0.3)
    axes[0].set_xlim([0, duration * 1000])

    # Plot 2: PWM signal (zoomed to show detail)
    zoom_duration = min(5 / f_tri, duration)  # Show 5 triangle periods or less
    zoom_mask = t <= zoom_duration
    axes[1].plot(t[zoom_mask] * 1000, pwm[zoom_mask], "r-", linewidth=0.8)
    axes[1].set_ylabel("PWM Signal")
    axes[1].set_title(f"PWM Signal (first {zoom_duration*1000:.1f} ms)")
    axes[1].grid(True, alpha=0.3)
    axes[1].set_ylim([-0.1, 1.1])
    axes[1].set_xlim([0, zoom_duration * 1000])

    # Plot 3: Filtered output vs ideal triangle
    axes[2].plot(t * 1000, filtered, "g-", linewidth=2, label="Filtered PWM", alpha=0.8)
    axes[2].plot(t * 1000, ideal_triangle, "k--", linewidth=1.5, label="Ideal Triangle", alpha=0.6)
    axes[2].set_ylabel("Amplitude")
    axes[2].set_title("RC Filtered Output vs Ideal Triangle Wave")
    axes[2].legend(loc="upper right")
    axes[2].grid(True, alpha=0.3)
    axes[2].set_xlim([0, duration * 1000])

    # Plot 4: Error/difference
    error = filtered - ideal_triangle
    axes[3].plot(t * 1000, error * 100, "m-", linewidth=1)
    axes[3].set_xlabel("Time (ms)")
    axes[3].set_ylabel("Error (%)")
    axes[3].set_title("Difference between Filtered and Ideal Triangle")
    axes[3].grid(True, alpha=0.3)
    axes[3].set_xlim([0, duration * 1000])
    axes[3].axhline(y=0, color="k", linestyle="-", linewidth=0.5)

    plt.tight_layout()

    # Calculate error metrics
    rmse = np.sqrt(np.mean(error**2))
    max_error = np.max(np.abs(error))

    print("RESULTS")
    print("=" * 60)
    print(f"RMS Error:     {rmse*100:.4f}%")
    print(f"Max Error:     {max_error*100:.4f}%")
    print("=" * 60 + "\n")

    return t, pwm, filtered, ideal_triangle, fig


def frequency_analysis(f_tri=10, f_pwm=1000, R=10e3, C=10e-6):
    """
    Analyze frequency response of the RC filter
    """
    fc = 1 / (2 * np.pi * R * C)

    # Frequency range for analysis
    freqs = np.logspace(-1, np.log10(f_pwm * 10), 1000)

    # RC filter transfer function
    H = 1 / (1 + 1j * 2 * np.pi * freqs * R * C)
    magnitude_db = 20 * np.log10(np.abs(H))
    phase_deg = np.angle(H) * 180 / np.pi

    # Create Bode plot
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))
    fig.suptitle("RC Filter Frequency Response", fontsize=14, fontweight="bold")

    # Magnitude plot
    ax1.semilogx(freqs, magnitude_db, "b-", linewidth=2)
    ax1.axvline(fc, color="r", linestyle="--", label=f'fc = {si_formatter(fc, "Hz")}')
    ax1.axvline(f_tri, color="g", linestyle="--", label=f'f_tri = {si_formatter(f_tri, "Hz")}')
    ax1.axvline(f_pwm, color="m", linestyle="--", label=f'f_pwm = {si_formatter(f_pwm, "Hz")}')
    ax1.set_ylabel("Magnitude (dB)")
    ax1.set_title("Magnitude Response")
    ax1.grid(True, alpha=0.3, which="both")
    ax1.legend()
    ax1.axhline(y=-3, color="k", linestyle=":", linewidth=1, alpha=0.5)

    # Phase plot
    ax2.semilogx(freqs, phase_deg, "b-", linewidth=2)
    ax2.axvline(fc, color="r", linestyle="--", label=f'fc = {si_formatter(fc, "Hz")}')
    ax2.axvline(f_tri, color="g", linestyle="--", label=f'f_tri = {si_formatter(f_tri, "Hz")}')
    ax2.axvline(f_pwm, color="m", linestyle="--", label=f'f_pwm = {si_formatter(f_pwm, "Hz")}')
    ax2.set_xlabel("Frequency (Hz)")
    ax2.set_ylabel("Phase (degrees)")
    ax2.set_title("Phase Response")
    ax2.grid(True, alpha=0.3, which="both")
    ax2.legend()

    plt.tight_layout()

    # Print attenuation at key frequencies
    print("\nFREQUENCY ANALYSIS")
    print("=" * 60)
    print(f"Filter cutoff frequency (fc): {si_formatter(fc, 'Hz')}")

    # Attenuation at triangle frequency
    H_tri = 1 / (1 + 1j * 2 * np.pi * f_tri * R * C)
    att_tri = 20 * np.log10(np.abs(H_tri))
    print(f"Attenuation at f_tri ({si_formatter(f_tri, 'Hz')}): {att_tri:.2f} dB")

    # Attenuation at PWM frequency
    H_pwm = 1 / (1 + 1j * 2 * np.pi * f_pwm * R * C)
    att_pwm = 20 * np.log10(np.abs(H_pwm))
    print(f"Attenuation at f_pwm ({si_formatter(f_pwm, 'Hz')}): {att_pwm:.2f} dB")
    print("=" * 60 + "\n")

    return fig


if __name__ == "__main__":
    # Simulation parameters
    F_TRIANGLE = 10  # Triangle wave frequency (Hz)
    F_PWM = 100  # PWM carrier frequency (Hz)
    R = 10e3  # 10 kΩ
    C = 1e-6  # 1 µF
    DURATION = 0.5  # 0.5 seconds

    # Run time-domain simulation
    t, pwm, filtered, ideal, fig1 = simulate_pwm_triangle_generation(f_tri=F_TRIANGLE, f_pwm=F_PWM, R=R, C=C, duration=DURATION)

    # Run frequency analysis
    fig2 = frequency_analysis(f_tri=F_TRIANGLE, f_pwm=F_PWM, R=R, C=C)

    plt.show()
